name: Build and Push Multi-Architecture Docker Image (Latest Build)

on:
  push:
    branches:
      - main
    paths:
      - 'garmin-fetch.py'
      - 'compose-example.yml'
      - 'requirements.txt'
      - 'Dockerfile'

env:
  IMAGE_NAME: garmin-fetch-data
  IMAGE_TAG: latest
  IMAGE_REPO: thisisarpanghosh

jobs:
  build_and_push:
    name: Build Multi-Arch Docker Image and Push to Docker Hub & GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU for Multi-Architecture Support
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Multi-Arch Image (linux/amd64, linux/arm64)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io # Explicitly mention the registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          docker push docker.io/${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io  # Explicitly mention the registry
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
